### ISSUE TITLE
XSalsa20Poly1305 vs AES

### ISSUE THREAD

**Issue by dalehamel** [cryptosphere/rbnacl#126]
First off, this is a really cool library. 

A coworker (and security expert) directed me here when he found out I was manually encrypting things with openssl aes-256-cbc. I replaced that functionality with rbnacl, and it's quite fast now.

My concern is that I don't know much about cryptography, aside from a single undergrad class. 

I'm curious why rbnacl opts for XSalsa20Poly1305 for the secretbox algorithm, rather than the more proven AES?

Again, I'm not an experienced cryptanalyst - I just want to make sure I'm making a responsible decision by not using something like aes-256-gcb / cbc.

In my use case, I'm encrypting squashfs system images.

**Comment by tarcieri** [comment]
XSalsa20Poly1305 is the default cipher provided by NaCl. It's a relatively uncontroversial stream cipher. Its successor, ChaCha20Poly1305, was recently added to TLS:

https://blog.cloudflare.com/do-the-chacha-better-mobile-performance-with-cryptography/

AES is a great cipher when implemented in hardware, but difficult to implement correctly in software. libsodium contains a number of AES functions we don't expose, mostly for lack of time/interest, but also because the high-level constructions NaCl/libsodium provides (i.e. crypto_box/crypto_secretbox) are not implemented for AES.

**Comment by dalehamel** [comment]
Thanks for the explanation!

I suppose sodium doesn't include the chacha cipher?

**Comment by tarcieri** [comment]
It does, but it hasn't been added to RbNaCl yet
